Add Julia client
Olical/conjure pull request #346
Opened 2022-04-25 06:30 UTC by TerseTears

This uses tree-sitter and the stdio approach. There are important drawbacks though that need fixing.

## What works:
- Evaluating current form
- Evaluating root form
- Showing documentation in log buffer

## Stdio issues:
- It seems that Julia doesn't send the prompt pattern (i.e. `julia>`) to stdout, hence the prompt needs to be set to the empty character `""`. Then the issue is that if a line prints nothing (such as `using Statistics`), conjure gets stuck.

## Tree-sitter issues:
- When there is an error in syntax, usually the root node is wrongly identified. For instance, when trying to send a line from the documentation:
![Screenshot_20220425_103319](https://user-images.githubusercontent.com/36173945/165029605-b1252184-73ec-4b87-809a-bf8c0031fc8c.png)
In the above, we do not want `julia>` to be sent as well.

## Other issues:
- Upon the first send, the log isn't properly updated and appears to get trimmed:
![Screenshot_20220425_102133](https://user-images.githubusercontent.com/36173945/165028410-b3a380b7-941e-42ff-a587-bf5130a91aa6.png)
- There is a conflict with the [julia-vim](https://github.com/JuliaEditorSupport/julia-vim) plugin for the key `K`. julia-vim uses wordprg while `K` in conjure simply sends the doc to the log. Maybe a different mapping can be used by conjure?

## Ideas:
- There is a [RemoteREPL](https://github.com/c42f/RemoteREPL.jl) julia package which may provide the facilities to take a more robust approach than stdio.  [REPL](https://github.com/JuliaLang/julia/blob/master/stdlib/REPL/src/REPL.jl) itself is a module in Julia's stdlib which might be sufficient.
- Should new clients generally be separate plugins or is it okay to just merge all of them in conjure?

Related issue Olical/Conjure#184 and ping to the author @savq.

2022-05-01 21:33 UTC, savq commented
Hey @TerseTears,

This is really cool. Thanks for working on this and for letting me know.

> For instance, when trying to send a line from the documentation:
In the above, we do not want julia> to be sent as well.

The repl strips the prompt when pasting things, I guess you could do something similar like `(gsub str "^julia> " "")`, but that doesn't seem super important to me.

> There is a [RemoteREPL](https://github.com/c42f/RemoteREPL.jl) julia package which may provide the facilities to take a more robust approach than stdio

RemoteREPL makes a  julia-julia connection. At some point I tried using [Neovim.jl](https://github.com/bfredl/Neovim.jl) for a julia-nvim connection, which worked mostly fine. There's a small bug, but it should be fixable (the api has to be updated to 0.7 anyways).

> Should new clients generally be separate plugins or is it okay to just merge all of them in conjure?

I'd support making this a separate plugin for now.

2022-05-02 09:08 UTC, Olical commented
I'll look into this more today but quickly:

 * I'm happy with this being a PR or a plugin you'd install alongside. The only downside to the PR approach for you is that I'd like to review things before they go in, so a plugin might help you iterate faster but I do like all of the core languages being part of one big system that lazily loads what it needs. So do what works best for you but I like what you're doing right now 😄 
 * The on-stray-output receiving a string instead of a table of strings sounds familiar, another Neovim function had a breaking change recently I think, or made me use another function that works similar but returns a single string instead of a table of them. So I wonder if maybe adapting to that Neovim breaking change / fn deprecation caused a ripple of bugs like this.

2022-05-02 14:53 UTC, Olical commented
No commit squashing required! I like commits as they are as long as they're descriptive enough 😄 

Before I really dig into this it'd be great is someone else with a vested interest in this client could also confirm that your fork works for them, just to make sure there's enough information here for someone who knows the language and tools to work with it. If so I'll feel confident spending time verifying the support for myself / installing the toolchain / learning the basics of the language.

2022-05-02 14:54 UTC, Olical commented
@savq if you do have a little time, I'd love it if you could give us a +1 if you can get this working in your setup 😄

2022-05-03 20:08 UTC, savq requested changes
It's working very well for me. I'm running
```
julia 1.7.2
neovim 0.7.0
```

I wrote separate comments for the things that might need revision.

2022-05-03 20:08 UTC, savq commented on fnl/conjure/client/julia/stdio.fnl
> +      :command "julia --banner=no --color=no -i"
suggestion: Might be a good idea to add `--project=@.` so the repl uses in the project environment of the current directory.

2022-05-03 20:08 UTC, savq commented on fnl/conjure/client/julia/stdio.fnl
> +       (.. "|> display" "\n")))
issue: This will fail if the string ends with a semi-colon. Might be better to interpolate than to concatenate.

2022-05-03 20:08 UTC, savq commented on fnl/conjure/client/julia/stdio.fnl
> +(defn format-msg [msg]
Evaluating `println("foo")` results in
```
foonothing
```
So the result value needs a newline when there's something in stdout, but no newline otherwise.

2022-05-06 12:07 UTC, TerseTears commented on fnl/conjure/client/julia/stdio.fnl
> +       (.. "|> display" "\n")))
This should be fixed by a17fb27dd79ecc3ed672338e05c6d017dbe7c6c6.

2022-05-06 12:08 UTC, TerseTears commented on fnl/conjure/client/julia/stdio.fnl
> +(defn format-msg [msg]
The a4303af0da721aff8c3f3d1e6b528f21fb640b71 should fix this.

2022-05-06 12:09 UTC, TerseTears commented on fnl/conjure/client/julia/stdio.fnl
> +      :command "julia --banner=no --color=no -i"
I checked the manpage for Julia 1.7.2 and `@.` seems to be the default now.

2022-05-06 12:25 UTC, TerseTears commented
I still have an issue with stray output. I don't know why the first time a form is sent to the REPL it goes to stray output. Might be an issue with the Julia REPL, but the output is received in disparate parts and since `log.append` has its own way of connecting these parts, the result isn't the same as the second time the form is sent to the REPL. I'm using the `join-first` option as an interim remedy. This is how the debug log looks like:

```fennel
# --------------------------------------------------------------------------------
# eval (selection): a = 2; b = 9; mat2 = [9 7] mat1...
# debug: send
"a = 2; 
b = 9;
mat2 = [9 7]
mat1 = [2, 4]

if(isnothing(ans)) display(nothing) end
"
# debug: receive
"out" nil "2"
# debug: msg in format-msg:
"2"
2
# debug: receive
"out" nil "
9
"
# debug: on-stray-output-fn:
""
# debug: msg in format-msg:
"
9
"9
# debug: receive
"out" nil "1×2 "
# debug: on-stray-output-fn:
""
# debug: msg in format-msg:
"1×2 "1×2 
# debug: receive
"out" nil "Matrix{"
# debug: on-stray-output-fn:
""
# debug: msg in format-msg:
"Matrix{"Matrix{
# debug: receive
"out" nil "Int64}:"
# debug: on-stray-output-fn:
""
# debug: msg in format-msg:
"Int64}:"Int64}:
# debug: receive
"out" nil "
"
# debug: on-stray-output-fn:
""
# debug: msg in format-msg:
"
"
# debug: receive
"out" nil " "
# debug: on-stray-output-fn:
""
# debug: msg in format-msg:
" " 
# debug: receive
"out" nil "9  "
# debug: on-stray-output-fn:
""
# debug: msg in format-msg:
"9  "9  
# debug: receive
"out" nil "7
"
# debug: on-stray-output-fn:
""
# debug: msg in format-msg:
"7
"7
# debug: receive
"out" nil "2-element "
# debug: on-stray-output-fn:
""
# debug: msg in format-msg:
"2-element "2-element 
# debug: receive
"out" nil "Vector{Int64}:
 2
 4
nothing"
# debug: on-stray-output-fn:
""
# debug: msg in format-msg:
"Vector{Int64}:
 2
 4
nothing"Vector{Int64}:
 2
 4
```

This isn't a great issue though, it's just sort of inconvinient to have to resend the form to see the results as displayed by the Julia REPL.

2022-05-12 21:33 UTC, savq approved these changes
Looks good to me!

The stray output thingie seems to only affect collections. Using `show` instead of `display` might fix it, but then the output wouldn't look like it does in the repl. I agree that it's not a serious issue.

2022-05-28 09:58 UTC, Olical commented
Okay, so, what do you think about merging and releasing this to get it in users hands so we can iterate? Can always ship it with the caveat of "it'll try it's best over stdio but it's hard to catch all output with this transport" then maybe one day this can be slowly replaced with some nREPL client or something for Julia if it ever gets one?

Happy with the code and behaviour right now? I'm going to defer to the judgement of @TerseTears and @savq since it's a new client and I don't know much about it. I'll handle any extra documentation / wiki / readme changes if they're required.

2022-05-28 12:39 UTC, Olical commented
Oh you might want to check out the use of `form-node?` around the existing codebase now as well as in `:h conjure`. You can use that as a hook in your client to get Conjure to skip non-evaluateable leafs in your code. So if you add `(defn form-node? ...)` into your client Conjure will call it every time the user tries to eval a form. If you return `false` for the given ts node argument it'll walk up one level and ask again.

You can turn the ts node into a string and try to work with that (like I do for all lisps, I check if they being and end with pairs of things) or you can walk around the node trying to find something that tells you it can be evaluated. I hope this helps improve the eval semantics! Maybe you weren't having issues with this anyway, but thought I'd mention it, it's just a way for every individual client to configure which kinds of ts nodes are selected as the "form under the cursor" for eval.

2022-05-28 14:04 UTC, TerseTears commented
> Okay, so, what do you think about merging and releasing this to get it in users hands so we can iterate? Can always ship it with the caveat of "it'll try it's best over stdio but it's hard to catch all output with this transport" then maybe one day this can be slowly replaced with some nREPL client or something for Julia if it ever gets one?
> 
> Happy with the code and behaviour right now? I'm going to defer to the judgement of @TerseTears and @savq since it's a new client and I don't know much about it. I'll handle any extra documentation / wiki / readme changes if they're required.

I think it's a matter of quantity vs quality in this case. The tree-sitter implementation allows writing clients essentially for all languages supported by tree-sitter. I've also been experimenting with a client for R. Implementing a client by the stdio approach is very easy, and I had little trouble figuring out what was needed. But it is always inferior to directly communicating with the REPL. Like, I couldn't figure out in the end how to switch the REPL mode by the stdio approach for Julia. Or in the case of R, a plugin that directly communicates with R such as Nvim-R (through a TCP server) can do a lot of other things as well.

I'm somewhat convinced the stray output issue is due to the Julia REPL itself, as hy and the R client do not exhibit the same behaviour.

My only remaining issue is that the inline result shows only the last line of the result but that is a separate issue with conjure I believe.

I also regret not having prefixed my commits with `julia: ` so if there's a least destructive way to fix that, please do let me know.

2022-05-28 14:05 UTC, TerseTears commented
> Oh you might want to check out the use of `form-node?` around the existing codebase now as well as in `:h conjure`. You can use that as a hook in your client to get Conjure to skip non-evaluateable leafs in your code. So if you add `(defn form-node? ...)` into your client Conjure will call it every time the user tries to eval a form. If you return `false` for the given ts node argument it'll walk up one level and ask again.
> 
> You can turn the ts node into a string and try to work with that (like I do for all lisps, I check if they being and end with pairs of things) or you can walk around the node trying to find something that tells you it can be evaluated. I hope this helps improve the eval semantics! Maybe you weren't having issues with this anyway, but thought I'd mention it, it's just a way for every individual client to configure which kinds of ts nodes are selected as the "form under the cursor" for eval.

This is certainly useful. Then I should see how to use the function properly and rebase unto develop.

2022-07-02 10:47 UTC, Olical commented
Let's merge this and get it into users hands + make it easier for anyone (including myself) to iterate on it 😄

2022-07-02 10:48 UTC, merged

2022-07-03 10:50 UTC, Olical commented
It works really well with tree sitter! Great job! :D I'm just adding it to all of the docs and wiki pages now.